// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Xpathed.ClientApi.Data;

#nullable disable

namespace Xpathed.ClientApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260930163320_InitialDiagnostics")]
    partial class InitialDiagnostics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Xpathed.ClientApi.Data.DiagnosticRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceAvailability")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset?>("EvidenceExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImportHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("PageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProvenanceJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceExpiresAt");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("PageId", "CreatedAt");

                    b.ToTable("diagnostic_records", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
