<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Xpathed.ClientApi</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Common/Common.csproj" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>
</Project>
