<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Xpathed.Resolver</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Prompts/*" />
    <ProjectReference Include="../Common/Common.csproj" />
    <InternalsVisibleTo Include="Resolver.Tests" />
  </ItemGroup>
</Project>
